[package]
name = "uu_chcpu"
version = "0.0.1"
edition = "2024"

[lib]
path = "src/chcpu.rs"

[[bin]]
name = "chcpu"
path = "src/main.rs"

[dependencies]
uucore = { workspace = true }
clap = { workspace = true }
rangemap = { workspace = true }
